version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
      target: runner
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # Production service with custom port
  app-prod-custom:
    build:
      context: .
      target: runner
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod-custom

networks:
  default:
    driver: bridge 